### ISSUE TITLE
Unable to converge node using test-kitchen, chef_zero

### ISSUE THREAD

**Issue by 4-20ma** [chef-cookbooks/client-rekey#5]
I love the idea of this cookbook, especially after the revelation of the OpenSSL heartbleed bug. Rekeying clients periodically seems like a good idea. I'm unable to test this cookbook using the stock `.kitchen.yml` file for the following reasons:
- the provisioner is using `chef_solo` so I switched it to `chef_zero`
- I happen to be using Parallels so I cannot use VirtualBox simultaneously so I added a platform for my parallels VM; I don't believe this problem is related to my choice of VM
- the `run_list` is empty so I populated it with the default recipe
- I adjusted the client-rekey interval to 0 to force it to be updated; **otherwise the chef run converges successfully**

``` yaml

---
driver:
  name: vagrant

provisioner:
  name: chef_zero # changed this line

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: centos-6.5 # added this platform
    driver:
      provider: parallels
      box: parallels/centos-6.5

suites:
  - name: default
    run_list:
      - 'recipe[client-rekey]' # added this recipe
    attributes:
      'client-rekey':
        interval: 0 # added this attribute
```

This is the error I get when converging the node:

```
       [2014-05-14T06:12:45-05:00] INFO: HTTP Request Returned 404 Not Found : Object not found: http://127.0.0.1:8889/clients/default-centos-65

       ================================================================================
       Error executing action `run` on resource 'ruby_block[rekey-this-client]'
       ================================================================================


       Net::HTTPServerException
       ------------------------
       404 "Not Found "


       Cookbook Trace:
       ---------------
       /tmp/kitchen/cache/cookbooks/client-rekey/libraries/rekey.rb:79:in `update'
       /tmp/kitchen/cache/cookbooks/client-rekey/libraries/rekey.rb:51:in `run'
       /tmp/kitchen/cache/cookbooks/client-rekey/recipes/default.rb:29:in `block (2 levels) in from_file'


       Resource Declaration:
       ---------------------
       # In /tmp/kitchen/cache/cookbooks/client-rekey/recipes/default.rb

        23: ruby_block "rekey-this-client" do
        24:   node_name = Chef::Config[:node_name]
        25:   client_key = Chef::Config[:client_key]
        26: 
        27: 
        28:   block do
        29:     Chef::ApiClient::Rekey.new(node_name, client_key).run
        30:     Chef::Log.info "Client key updated"
        31:   end
        32: 
        33:   last_rekey = File.mtime(client_key)
        34:   now = Time.now
        35: 
        36:   difference = now - last_rekey
        37:   Chef::Log.info "Time since rekey: #{difference}"
        38: 
        39:   only_if { difference > node["client-rekey"]["interval"] }
        40: end



       Compiled Resource:
       ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/client-rekey/recipes/default.rb:23:in `from_file'

       ruby_block("rekey-this-client") do
         action "run"
         retries 0
         retry_delay 2
         guard_interpreter :default
         block_name "rekey-this-client"
         cookbook_name "client-rekey"
         recipe_name "default"
         block #<Proc:0x00000002eb4798@/tmp/kitchen/cache/cookbooks/client-rekey/recipes/default.rb:28>
         only_if { #code block }
       end



       [2014-05-14T06:12:45-05:00] INFO: Running queued delayed notifications before re-raising exception

       Running handlers:
       [2014-05-14T06:12:45-05:00] ERROR: Running exception handlers
       Running handlers complete

       [2014-05-14T06:12:45-05:00] ERROR: Exception handlers complete
       [2014-05-14T06:12:45-05:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 1.888901883 seconds
       [2014-05-14T06:12:45-05:00] ERROR: ruby_block[rekey-this-client] (client-rekey::default line 23) had an error: Net::HTTPServerException: 404 "Not Found "
       [2014-05-14T06:12:45-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-centos-65>.
>>>>>> Please see .kitchen/logs/default-centos-65.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sudo -E chef-client -z --config /tmp/kitchen/client.rb --log_level info --json-attributes /tmp/kitchen/dna.json]
>>>>>> ----------------------
```

Am I doing something wrong or is it possible that the cookbook doesn't handle chef-zero properly? Do I need to submit a COOK ticket?

**Comment by tas50** [comment]
This cookbook is built for chef server and most likely won't work in the simplified chef zero environment.
